version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=danielquimicah@hotmail.com
      - N8N_BASIC_AUTH_PASSWORD=Daniel@1993
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
    volumes:
      - ./dados-n8n:/home/node/.n8n